import { useEffect, useState, useRef } from 'react';
import { useAuth } from '../../context/AuthContext';
import { LineChart, Line, XAxis, YAxis, CartesianGrid, Tooltip, ResponsiveContainer } from 'recharts';
import html2canvas from 'html2canvas';
import jsPDF from 'jspdf';
import { Download, FileText, Share2 } from 'lucide-react';

const ReportView = () => {
  const { user } = useAuth();
  const [logs, setLogs] = useState([]);
  const [aiSummary, setAiSummary] = useState("Generating clinical summary based on your recent logs...");
  const [loading, setLoading] = useState(true);
  
  const reportRef = useRef(); // The element we will convert to PDF

  useEffect(() => {
    const fetchData = async () => {
      try {
        // 1. Fetch Logs
        const logRes = await fetch('http://localhost:5000/api/logs', {
           headers: { 'Authorization': `Bearer ${user.token}` }
        });
        const logData = await logRes.json();
        const sortedLogs = logData.reverse(); // Chronological order
        setLogs(sortedLogs);

        // 2. Fetch AI Clinical Summary
        // We reuse the Chat endpoint but with a strict "Doctor" system prompt
        const prompt = `
          ACT AS A DOCTOR. Review these health logs (Mood, Sleep, Diet) for patient ${user.name}. 
          Write a 3-paragraph clinical summary suitable for a medical report. 
          Focus on: 1. Sleep Hygiene, 2. Mood Stability, 3. Dietary Patterns. 
          Do not use markdown. Keep it professional and objective.
          LOGS: ${JSON.stringify(sortedLogs.slice(-5))}
        `;

        const aiRes = await fetch('http://localhost:5000/api/ai/chat', {
          method: 'POST',
          headers: {
            'Content-Type': 'application/json',
            'Authorization': `Bearer ${user.token}`
          },
          body: JSON.stringify({ message: prompt })
        });
        const aiData = await aiRes.json();
        setAiSummary(aiData.response);

      } catch (error) {
        console.error("Report generation failed", error);
        setAiSummary("Could not generate AI summary at this time.");
      } finally {
        setLoading(false);
      }
    };

    fetchData();
  }, [user]);

  const handleDownloadPDF = async () => {
    const element = reportRef.current;
    const canvas = await html2canvas(element, { scale: 2 }); // Scale 2 for high res
    const data = canvas.toDataURL('image/png');
    
    const pdf = new jsPDF('p', 'mm', 'a4');
    const imgProperties = pdf.getImageProperties(data);
    const pdfWidth = pdf.internal.pageSize.getWidth();
    const pdfHeight = (imgProperties.height * pdfWidth) / imgProperties.width;
    
    pdf.addImage(data, 'PNG', 0, 0, pdfWidth, pdfHeight);
    pdf.save(`Health_Report_${user.name}_${new Date().toISOString().split('T')[0]}.pdf`);
  };

  const chartData = logs.map(log => ({
    date: new Date(log.date).toLocaleDateString('en-US', { day: 'numeric', month: 'short' }),
    mood: log.mood.score,
    sleep: log.sleep.hours
  }));

  if (loading) return <div className="min-h-screen flex items-center justify-center text-[#4EC5C1] font-bold">Preparing your report...</div>;

  return (
    <div className="bg-gray-100 min-h-screen p-8 flex justify-center">
      
      {/* Action Bar */}
      <div className="fixed top-6 right-6 flex flex-col gap-3 z-50">
        <button 
          onClick={handleDownloadPDF}
          className="bg-[#1A3C40] text-white p-4 rounded-full shadow-xl hover:bg-[#142e32] transition tooltip"
          title="Download PDF"
        >
          <Download size={24} />
        </button>
      </div>

      {/* A4 Report Container */}
      <div 
        ref={reportRef} 
        className="bg-white w-[210mm] min-h-[297mm] p-[15mm] shadow-2xl text-gray-800 font-inter"
      >
        {/* Header */}
        <div className="border-b-2 border-[#4EC5C1] pb-6 mb-8 flex justify-between items-end">
          <div>
            <h1 className="text-3xl font-bold text-[#1A3C40] uppercase tracking-wide">Health Progress Report</h1>
            <p className="text-sm text-gray-500 mt-1">Generated by AI Health Tracker Platform</p>
          </div>
          <div className="text-right">
            <h2 className="text-xl font-bold">{user.name}</h2>
            <p className="text-sm text-gray-500">Report Date: {new Date().toLocaleDateString()}</p>
          </div>
        </div>

        {/* AI Clinical Summary */}
        <section className="mb-10 bg-[#F4F7F8] p-6 rounded-xl border border-gray-200">
          <h3 className="flex items-center gap-2 text-[#1A3C40] font-bold text-lg mb-3">
            <FileText size={20} /> AI Clinical Summary
          </h3>
          <p className="text-sm leading-relaxed text-gray-700 whitespace-pre-line text-justify">
            {aiSummary}
          </p>
        </section>

        {/* Visuals */}
        <section className="mb-10">
          <h3 className="text-[#1A3C40] font-bold text-lg mb-4">Vitals & Trends (Last 7 Days)</h3>
          
          <div className="grid grid-cols-2 gap-8">
            <div className="h-48">
              <h4 className="text-xs font-bold text-center uppercase text-gray-400 mb-2">Mood Stability</h4>
              <ResponsiveContainer width="100%" height="100%">
                <LineChart data={chartData}>
                  <CartesianGrid strokeDasharray="3 3" vertical={false} />
                  <XAxis dataKey="date" tick={{fontSize: 10}} />
                  <YAxis domain={[0, 10]} hide />
                  <Line type="monotone" dataKey="mood" stroke="#4EC5C1" strokeWidth={3} dot={{r: 4, fill: '#1A3C40'}} isAnimationActive={false} />
                </LineChart>
              </ResponsiveContainer>
            </div>

            <div className="h-48">
              <h4 className="text-xs font-bold text-center uppercase text-gray-400 mb-2">Sleep Hygiene</h4>
              <ResponsiveContainer width="100%" height="100%">
                <LineChart data={chartData}>
                  <CartesianGrid strokeDasharray="3 3" vertical={false} />
                  <XAxis dataKey="date" tick={{fontSize: 10}} />
                  <YAxis domain={[0, 12]} hide />
                  <Line type="step" dataKey="sleep" stroke="#1A3C40" strokeWidth={3} dot={{r: 4, fill: '#4EC5C1'}} isAnimationActive={false} />
                </LineChart>
              </ResponsiveContainer>
            </div>
          </div>
        </section>

        {/* Detailed Logs Table */}
        <section>
          <h3 className="text-[#1A3C40] font-bold text-lg mb-4">Detailed Daily Logs</h3>
          <table className="w-full text-sm text-left">
            <thead className="bg-[#1A3C40] text-white">
              <tr>
                <th className="p-3 rounded-tl-lg">Date</th>
                <th className="p-3">Mood</th>
                <th className="p-3">Sleep</th>
                <th className="p-3 rounded-tr-lg">Notes</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-gray-100">
              {logs.map((log) => (
                <tr key={log._id}>
                  <td className="p-3 font-medium">{new Date(log.date).toLocaleDateString()}</td>
                  <td className="p-3">
                    <span className="px-2 py-1 rounded-full bg-gray-100 text-xs font-bold">
                      {log.mood.score}/10 {log.mood.label}
                    </span>
                  </td>
                  <td className="p-3">{log.sleep.hours} hrs</td>
                  <td className="p-3 text-gray-500 italic truncate max-w-[200px]">{log.mood.note || '-'}</td>
                </tr>
              ))}
            </tbody>
          </table>
        </section>

        {/* Footer */}
        <div className="mt-12 pt-6 border-t border-gray-200 text-center text-xs text-gray-400">
          <p>End of Report • Generated via AI Health Tracker • Consult a medical professional for advice.</p>
        </div>

      </div>
    </div>
  );
};

export default ReportView;