import React from 'react';
import { Scale, AlertCircle, CheckCircle, Book } from 'lucide-react';

const TermsOfService = () => {
  return (
    <div className="min-h-screen bg-[#F4F7F8] dark:bg-[#0F172A] pt-24 pb-12 px-6 transition-colors duration-300">
      <div className="max-w-4xl mx-auto bg-white dark:bg-gray-800 rounded-3xl shadow-sm border border-gray-100 dark:border-gray-700 p-8 md:p-12">
        
        <div className="text-center mb-12">
          <div className="w-16 h-16 bg-blue-100 dark:bg-blue-900/30 text-blue-600 rounded-2xl flex items-center justify-center mx-auto mb-4">
            <Scale size={32} />
          </div>
          <h1 className="text-3xl md:text-4xl font-bold text-gray-900 dark:text-white mb-2">Terms of Service</h1>
          <p className="text-gray-500 dark:text-gray-400">Please read carefully before using HealthAI.</p>
        </div>

        <div className="space-y-8 text-gray-700 dark:text-gray-300 leading-relaxed">
          <section className="bg-yellow-50 dark:bg-yellow-900/20 p-6 rounded-xl border border-yellow-100 dark:border-yellow-800">
            <h2 className="text-lg font-bold text-yellow-800 dark:text-yellow-200 mb-2 flex items-center gap-2">
              <AlertCircle size={20} /> Medical Disclaimer
            </h2>
            <p className="text-sm">
              The AI Health Coach and reports generated by this platform are for informational purposes only. They are <strong>not a substitute for professional medical advice</strong>, diagnosis, or treatment. Always seek the advice of your physician.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-gray-900 dark:text-white mb-3">1. Acceptance of Terms</h2>
            <p>
              By accessing or using HealthAI, you agree to be bound by these Terms. If you disagree with any part of the terms, you may not access the service.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-gray-900 dark:text-white mb-3">2. User Accounts</h2>
            <p>
              You are responsible for safeguarding the password that you use to access the service and for any activities or actions under your password.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-gray-900 dark:text-white mb-3">3. Acceptable Use</h2>
            <p>
              You agree not to misuse the platform, including but not limited to: posting harmful content in the community, attempting to hack the service, or using the AI for illegal activities.
            </p>
          </section>
        </div>
      </div>
    </div>
  );
};

export default TermsOfService;