const PDFDocument = require('pdfkit');
const { formatDate } = require('../utils/dateFormatter');

const generateHealthPDF = (user, logs, res) => {
  const doc = new PDFDocument();

  // Pipe PDF directly to the response
  doc.pipe(res);

  // Header
  doc.fontSize(25).text('HealthAI Report', { align: 'center' });
  doc.moveDown();
  doc.fontSize(12).text(`Generated for: ${user.name}`);
  doc.text(`Date: ${formatDate(new Date())}`);
  doc.moveDown();
  doc.moveTo(50, 150).lineTo(550, 150).stroke(); // Horizontal Line

  // Summary Section
  doc.moveDown();
  doc.fontSize(16).text('Weekly Summary');
  doc.fontSize(12);
  
  const avgMood = logs.length 
    ? (logs.reduce((acc, log) => acc + (log.mood?.score || 0), 0) / logs.length).toFixed(1) 
    : 0;
  
  const totalSleep = logs.reduce((acc, log) => acc + (log.sleep?.hours || 0), 0);
  const avgSleep = logs.length ? (totalSleep / logs.length).toFixed(1) : 0;

  doc.text(`• Average Mood Score: ${avgMood}/10`);
  doc.text(`• Average Sleep: ${avgSleep} hours`);
  doc.text(`• Total Entries Logged: ${logs.length}`);
  doc.moveDown();

  // Logs Details
  doc.fontSize(16).text('Daily Logs');
  doc.moveDown();

  logs.forEach((log) => {
    doc.fontSize(14).text(formatDate(log.date), { underline: true });
    doc.fontSize(10);
    doc.text(`  Mood: ${log.mood?.label || 'N/A'} (${log.mood?.score || 0}/10)`);
    doc.text(`  Sleep: ${log.sleep?.hours || 0} hrs - ${log.sleep?.quality || 'N/A'}`);
    if (log.diet && log.diet.length > 0) {
      doc.text(`  Diet: ${log.diet[0].mealName || 'Logged'}`);
    }
    doc.moveDown(0.5);
  });

  // Footer
  doc.fontSize(10).text('Generated by AI Health Tracker Platform', 50, 700, { align: 'center', width: 500 });

  doc.end();
};

module.exports = { generateHealthPDF };